Fix null property deref in OneTableArgError
`context` argument is allowed to be null or undefined by type definition, and many callers (e.g., Table.js)
use the `message`-only constructor, so the deref of `.code` needs to use the null/undef-safe operator `?.`

Discovered by feeding a "works with an older version" schema to the `Table` constructor and getting
```
TypeError: Cannot read property 'code' of undefined
    at new OneTableArgError
```